spring:
  application:
    name: supportapp

  cache:
    type: simple

  datasource:
    url: jdbc:postgresql://localhost:5432/supportTicket
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

security:
  content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data;"
  permissions-policy: "camera=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), sync-xhr=()"
  authentication:
    jwt:
      base64-secret: ZjQ5ZjY5MDBkNTZlMzcwNDlmNzc3Njc5YmRmNzQwMzQ4NmUzZjQxNzI1YjFjMWM0NTAxY2FiOWExOTFkYjA0ZmM0MzQwY2MyNWY0NzYwNzNhZDg4ODUxMjllYmZiZTEwNzBiNWU1OWE4MWFiYmJlZTA3MGUxNzQyMGEwZDgwMmQ=
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 2592000
server:
  port: 8081